---
kind: pipeline
type: kubernetes
name: default

workspace:
  path: /ecr-docker-login

metadata:
  namespace: drone
  labels:
    app: ecr-docker-login
  annotations:
    iam.amazonaws.com/role: k8s-drone
service_account_name: drone-shazam

#volumes:
#  - name: host-var-run
#    host:
#      path: /var/run

steps:
  - name: build
    image: 539703851677.dkr.ecr.us-west-2.amazonaws.com/rust-musl:2020-02-04
    commands:
      - apt-get update && apt-get install -y python3-pip && pip3 install awscli
      - cargo build --release
      - aws s3 cp target/x86_64-unknown-linux-musl/release/ecr-docker-login
