---
kind: pipeline
type: kubernetes
name: default

workspace:
  path: /ecr-docker-login

metadata:
  namespace: drone
  labels:
    app: ecr-docker-login
  annotations:
    iam.amazonaws.com/role: k8s-drone
service_account_name: drone-shazam

volumes:
  - name: docker-sock
    host: /var/run/docker.sock

steps:
  - name: build
    image: docker:stable
    environment:
      DEBIAN_FRONTEND: noninteractive
      AWS_REGION: us-west-2
    volume:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - sleep infinity
