---
kind: pipeline
type: kubernetes
name: default

workspace:
  path: /aws-ci-buddy

metadata:
  namespace: drone
  labels:
    app: aws-ci-buddy
  annotations:
    iam.amazonaws.com/role: k8s-drone
service_account_name: drone-shazam

#volumes:
#  - name: host-var-run
#    host:
#      path: /var/run

steps:
  - name: build
    image: 539703851677.dkr.ecr.us-west-2.amazonaws.com/rust-musl:2020-02-04
    commands:
      - echo ${CI_COMMIT_SHA:0:8}
      - sudo apt-get update && sudo apt-get install -y python3-pip && sudo pip3 install awscli
      - cargo build --release
      - aws s3 cp --no-progress --acl=public-read target/x86_64-unknown-linux-musl/release/aws-ci-buddy s3://ids-dev-artifacts/aws-ci-buddy/${CI_COMMIT_SHA:0:8}/aws-ci-buddy
